# Generated by Django 3.0.2 on 2021-10-25 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('funding_method', models.CharField(choices=[('none', 'Select Method'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'USDT(Tether)')], default='none', max_length=7)),
                ('funding_amount', models.CharField(choices=[('none', 'Select Amount'), ('200', '200'), ('500', '500'), ('1000', '1,000'), ('5000', '5,000'), ('10000', '10,000')], default='none', max_length=15)),
                ('withdrawal_amount', models.CharField(max_length=15, null=True)),
                ('withdrawal_method', models.CharField(choices=[('none', 'Select Method'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'USDT(Tether)')], default='none', max_length=15)),
                ('btc_address', models.CharField(blank=True, max_length=500, null=True)),
                ('eth_address', models.CharField(blank=True, max_length=500, null=True)),
                ('usdt_address', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
