# Generated by Django 3.0.2 on 2021-10-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='funding_amount',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='funding_method',
        ),
        migrations.AddField(
            model_name='profile',
            name='fund_amount',
            field=models.CharField(choices=[('none', 'Select Amount'), ('200', '200'), ('500', '500'), ('1000', '1,000'), ('5000', '5,000'), ('10000', '10,000')], default='none', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='fund_method',
            field=models.CharField(choices=[('none', 'Select Method'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'USDT(Tether)')], default='none', max_length=7),
        ),
    ]
